version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8020:8020'
    environment:
      postgres_host: postgres
      postgres_user: postgres
      postgres_pass: letmein
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      ethereum: 'xdai:https://rpc.gnosischain.com'
      GRAPH_LOG: info
      GRAPH_ALLOW_NON_DETERMINISTIC_IPFS: 'true'
      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"
      LC_COLLATE: C
      LC_CTYPE: C
    depends_on:
      - ipfs
      - postgres
      - ganache
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: letmein
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"
      LC_COLLATE: C
      LC_CTYPE: C
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
  ganache:
    image: trufflesuite/ganache-cli
    command: "-d -i 50"
    ports:
      - '7545:8545'
  hg-subgraph:
    build: ./docker/hg-subgraph/
    depends_on:
      - graph-node
  deploy-contracts:
    build: ./docker/deploy-contracts/
    command: "./prepare_db.sh"
    depends_on:
      - ganache